name: xcharts
version: 0.1.7
author: Graciliano Monteiro Passos <gracilianomp@gmail.com>
description: Another Charts library.
homepage: https://github.com/UpLibs/xcharts
dependencies:
  numerical_collection: ">=0.1.2 <0.2.0"

